### ISSUE TITLE
[Bug] Cannot process rectangular frames

### ISSUE THREAD

**Issue by SingleZombie** [G-U-N/Pix2Video.pytorch#1]
In the following line, the width and height are reversed.
https://github.com/G-U-N/Pix2Video.pytorch/blob/c6a9289f71e2ad5d2bfe9ac07a3208d6c51e7474/tuneavideo/pipelines/pipeline_pix2video.py#L385

With this bug, the script cannot process a video whose height and width are not equal.

**Comment by G-U-N** [comment]
Thanks for your advice, fixed.
