### ISSUE TITLE
[Error] ValueError: The image to be converted to a PIL image contains values outside the range [0, 1], got [0.0, 249.0] which cannot be converted to uint8.

### ISSUE THREAD

**Issue by rnjtsh** [G-U-N/Pix2Video.pytorch#2]
Trying to replicate the code in colab. Got this error:

2023-06-01 07:26:39.496884: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
06/01/2023 07:26:43 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

{'class_embed_type', 'resnet_time_scale_shift', 'upcast_attention', 'mid_block_type'} was not found in config. Values will be initialized to default values.
06/01/2023 07:27:33 - INFO - __main__ - inference pixel values
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/drive/MyDrive/GenVR/Pix2VideoGitHub/train_pix2video.py:182 in       │
│ <module>                                                                     │
│                                                                              │
│   179 │   parser.add_argument("--config", type=str, default="./configs/tunea │
│   180 │   args = parser.parse_args()                                         │
│   181 │                                                                      │
│ ❱ 182 │   main(**OmegaConf.load(args.config))                                │
│   183                                                                        │
│                                                                              │
│ /content/drive/MyDrive/GenVR/Pix2VideoGitHub/train_pix2video.py:160 in main  │
│                                                                              │
│   157 │   │   │   ddim_inv_latent = None                                     │
│   158 │   │   │   if validation_data.use_inv_latent:                         │
│   159 │   │   │   │   inv_latents_path = os.path.join(output_dir, f"inv_late │
│ ❱ 160 │   │   │   │   ddim_inv_latent = ddim_inversion(                      │
│   161 │   │   │   │   │   validation_pipeline_depth, ddim_inv_scheduler, vid │
│   162 │   │   │   │   │   num_inv_steps=validation_data.num_inv_steps, promp │
│   163 │   │   │   │   torch.save(ddim_inv_latent, inv_latents_path)          │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py:115 in    │
│ decorate_context                                                             │
│                                                                              │
│   112 │   @functools.wraps(func)                                             │
│   113 │   def decorate_context(*args, **kwargs):                             │
│   114 │   │   with ctx_factory():                                            │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                               │
│   116 │                                                                      │
│   117 │   return decorate_context                                            │
│   118                                                                        │
│                                                                              │
│ /content/drive/MyDrive/GenVR/Pix2VideoGitHub/tuneavideo/util.py:89 in        │
│ ddim_inversion                                                               │
│                                                                              │
│    86 def ddim_inversion(pipeline, ddim_scheduler, video_latent, num_inv_ste │
│    87 │   if pixel_values is not None:                                       │
│    88 │   │   video_length = video_latent.shape[2]                           │
│ ❱  89 │   │   depth_map = pipeline.prepare_depth_map(                        │
│    90 │   │   │   pixel_values,                                              │
│    91 │   │   │   None,                                                      │
│    92 │   │   │   1,                                                         │
│                                                                              │
│ /content/drive/MyDrive/GenVR/Pix2VideoGitHub/tuneavideo/pipelines/pipeline_p │
│ ix2video.py:388 in prepare_depth_map                                         │
│                                                                              │
│   385 │   │   │   width, height = image[0].shape[-2:]                        │
│   386 │   │                                                                  │
│   387 │   │   if depth_map is None:                                          │
│ ❱ 388 │   │   │   pixel_values = self.feature_extractor(images=image, return │
│   389 │   │   │   pixel_values = pixel_values.to(device=device)              │
│   390 │   │   │   # The DPT-Hybrid model uses batch-norm layers which are no │
│   391 │   │   │   # So we use `torch.autocast` here for half precision infer │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/image_processing_utils. │
│ py:464 in __call__                                                           │
│                                                                              │
│   461 │                                                                      │
│   462 │   def __call__(self, images, **kwargs) -> BatchFeature:              │
│   463 │   │   """Preprocess an image or a batch of images."""                │
│ ❱ 464 │   │   return self.preprocess(images, **kwargs)                       │
│   465 │                                                                      │
│   466 │   def preprocess(self, images, **kwargs) -> BatchFeature:            │
│   467 │   │   raise NotImplementedError("Each image processor must implement │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/models/dpt/image_proces │
│ sing_dpt.py:329 in preprocess                                                │
│                                                                              │
│   326 │   │   images = [to_numpy_array(image) for image in images]           │
│   327 │   │                                                                  │
│   328 │   │   if do_resize:                                                  │
│ ❱ 329 │   │   │   images = [self.resize(image=image, size=size, resample=res │
│   330 │   │                                                                  │
│   331 │   │   if do_rescale:                                                 │
│   332 │   │   │   images = [self.rescale(image=image, scale=rescale_factor)  │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/models/dpt/image_proces │
│ sing_dpt.py:329 in <listcomp>                                                │
│                                                                              │
│   326 │   │   images = [to_numpy_array(image) for image in images]           │
│   327 │   │                                                                  │
│   328 │   │   if do_resize:                                                  │
│ ❱ 329 │   │   │   images = [self.resize(image=image, size=size, resample=res │
│   330 │   │                                                                  │
│   331 │   │   if do_rescale:                                                 │
│   332 │   │   │   images = [self.rescale(image=image, scale=rescale_factor)  │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/models/dpt/image_proces │
│ sing_dpt.py:192 in resize                                                    │
│                                                                              │
│   189 │   │   │   keep_aspect_ratio=keep_aspect_ratio,                       │
│   190 │   │   │   multiple=ensure_multiple_of,                               │
│   191 │   │   )                                                              │
│ ❱ 192 │   │   return resize(image, size=output_size, resample=resample, data │
│   193 │                                                                      │
│   194 │   def rescale(                                                       │
│   195 │   │   self,                                                          │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/image_transforms.py:306 │
│ in resize                                                                    │
│                                                                              │
│   303 │   # the pillow library to resize the image and then convert back to  │
│   304 │   do_rescale = False                                                 │
│   305 │   if not isinstance(image, PIL.Image.Image):                         │
│ ❱ 306 │   │   do_rescale = _rescale_for_pil_conversion(image)                │
│   307 │   │   image = to_pil_image(image, do_rescale=do_rescale)             │
│   308 │   height, width = size                                               │
│   309 │   # PIL images are in the format (width, height)                     │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/image_transforms.py:141 │
│ in _rescale_for_pil_conversion                                               │
│                                                                              │
│   138 │   elif np.all(0 <= image) and np.all(image <= 1):                    │
│   139 │   │   do_rescale = True                                              │
│   140 │   else:                                                              │
│ ❱ 141 │   │   raise ValueError(                                              │
│   142 │   │   │   "The image to be converted to a PIL image contains values  │
│   143 │   │   │   f"got [{image.min()}, {image.max()}] which cannot be conve │
│   144 │   │   )                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: The image to be converted to a PIL image contains values outside the
range [0, 1], got [0.0, 249.0] which cannot be converted to uint8.

How to solve this?

**Comment by G-U-N** [comment]
I have changed the line 152  from
```python
pixel_values = (pixel_values+1)*127.5
```
to
```python
pixel_values = (pixel_values+1)/2
```
.
Now it should work.
